export const LOAD_PLANETS_SUCCESS = 'LOAD_PLANETS_SUCCESS';
export const LOAD_FILMS_SUCCESS = 'LOAD_FILMS_SUCCESS';
export const LOAD_RESIDENTS_SUCCESS = 'LOAD_RESIDENTS_SUCCESS';
export const LOAD_DETAIL_SUCCESS = 'LOAD_DETAIL_SUCCESS';
